
<meta charset="utf-8">

<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/wb/libs/ext/resources/ext-theme-gray/ext-theme-gray-all.css"></link>

<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/es/EnterpriseSheet/resources/css/common.css"></link>
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/es/EnterpriseSheet/resources/css/sheet.css"></link>
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/es/EnterpriseSheet/resources/css/toolbar.css"></link>

<script type="text/javascript" src="<%=request.getContextPath()%>/wb/libs/ext/ext-all.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/wb/libs/ext/locale/ext-lang-zh.js"></script>

<script type="text/javascript" src="<%=request.getContextPath()%>/es/EnterpriseSheet/src/EnterpriseSheet/Config.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/es/EnterpriseSheet/src/language/zh_CN.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/es/EnterpriseSheet/enterprisesheet.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/es/EnterpriseSheet/templates/CenterPanel.js"></script>